version: 2.1

executors:
  cpp-executor:
    docker:
      - image: ubuntu:latest
    environment:
      CC: clang
      CXX: clang++
      PATH: "/usr/local/bin:/usr/bin:/bin"
      DEBIAN_FRONTEND: noninteractive  # Ensures non-interactive installation
      TEST_RESULTS: /tmp/test-results

jobs:
  build_and_test:
    executor: cpp-executor
    steps:
      - checkout
      - run:
          name: Fix CA Certificates
          command: |
            apt update && apt install -y --no-install-recommends ca-certificates
            if command -v update-ca-certificates > /dev/null; then
              update-ca-certificates
            fi
      - run:
          name: Set timezone to UTC
          command: |
            ln -fs /usr/share/zoneinfo/UTC /etc/localtime
            echo "tzdata tzdata/Areas select Etc" | debconf-set-selections
            echo "tzdata tzdata/Zones/Etc select UTC" | debconf-set-selections
      - run:
          name: Install dependencies
          command: |
            apt update && apt install -y --no-install-recommends \
              build-essential \
              libtool \
              autoconf \
              clang \
              clang-tidy \
              clang-format \
              gcovr \
              lcov \
              ninja-build \
              curl \
              zip \
              unzip \
              tar \
              git \
              python3 \
              pkg-config \
              tzdata \
              wget \
              clang-18 llvm-18-dev libclang-18-dev
            CMAKE_VERSION=3.31.5
            CMAKE_TAR=cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz
            wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/${CMAKE_TAR}
            tar -xzvf ${CMAKE_TAR}
            mv cmake-${CMAKE_VERSION}-linux-x86_64 /opt/cmake
            export PATH=/opt/cmake/bin:$PATH
            which cmake
            cmake --version


      - run:
          name: Verify tar installation
          command: |
            tar --version
      - run:
          name: Install vcpkg with debug logs
          command: |
            set -x  # Enable debugging
            git clone https://github.com/microsoft/vcpkg.git
            ls -lah vcpkg  # Ensure vcpkg directory exists
            cat vcpkg/bootstrap-vcpkg.sh | head -n 40  # Show first 40 lines of the script for inspection
            ./vcpkg/bootstrap-vcpkg.sh || (echo "vcpkg bootstrap failed!" && exit 1)
      - run:
          name: Install project dependencies
          command: |
            ./vcpkg/vcpkg install gtest
      - run:
          name: Configure CMake
          command: |
            export PATH=/opt/cmake/bin:$PATH
            cmake -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_COMPILER=clang++
      - run:
          name: Build # check existence of any llvm lib
          command: |
            apt install llvm-18 clang-18
            apt install libclang-rt-18-dev -y
            echo "llvm any version check"
            ls /usr/lib/llvm-*/lib/clang/
            echo "!!!!!!!!!!!!!!!!!!!!!!!!below looking for lib path!!!!!!!!!"
            find /usr/lib -name "libclang_rt.profile-x86_64.a"
            echo "!!!!!!!!!!!!!!!!!!!!!!!!above looking for lib path!!!!!!!!!"
            export LIBRARY_PATH=/usr/lib/llvm-18/lib/clang/18/lib/linux:$LIBRARY_PATH
            export PATH=/opt/cmake/bin:$PATH
            cmake -B build -S . -DCMAKE_CXX_FLAGS="-L/usr/lib/llvm-18/lib/clang/18/lib/linux/"
            echo "below is verbose build fail message"
            cmake --build build -v
      - run:
          name: Run tests
          command: |
            export PATH=/opt/cmake/bin:$PATH
            which cmake
            cmake --version
            export GTEST_OUTPUT=xml:${TEST_RESULTS}/
            mkdir -p $TEST_RESULTS
            ctest --test-dir build --output-on-failure
      - store_test_results:
          path: /tmp/test-results
      - run:
          name: Run Clang-Format
          command: |
            clang-format --dry-run --Werror $(find Components/ -type f \( -name "*.cpp" -o -name "*.h" \) ! -path "Components/calculator.cpp") main.cpp

      - run:
          name: Run Clang-Tidy with Compilation Database
          command: |
            export PATH=/opt/cmake/bin:$PATH
            cd build
            cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=YES ..
            run-clang-tidy -p .
      - run:
          name: Generate Coverage
          command: |  # shouldn't need to run tests again.
            cd .. # get back out from build
            gcovr -r . --html --html-details -o coverage.html
            cat coverage.html
      - store_artifacts:
          path: coverage.html
          destination: coverage


workflows:
  version: 2
  cpp_pipeline:
    jobs:
      - build_and_test
